version: '3.8'

services:
  db:
    image: pgvector/pgvector:pg16
    container_name: internbot-db-dev
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: internbot
    ports:
      - "5432:5432"
    volumes:
      - pgdata_dev:/var/lib/postgresql/data
      - ./postgres/schema.sql:/docker-entrypoint-initdb.d/schema.sql

  backend:
    build: ./backend
    container_name: internbot-backend-dev
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: internbot
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    command: uvicorn intern_bot.api.api:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: internbot-frontend-dev
    depends_on:
      - backend
    ports:
      - "3000:3000"
    environment:
      - VITE_BACKEND_URL=http://localhost:8000
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  pgdata_dev:
